name: go-server-test
team: me-myself-and-i
replicas: 2
type: go-service
ingress:
  type: NodePort
  # type: ClusterIP
  selector:
    someotherThing: value
  ports:
  - port: 3000
    nodePort: 32444
config:
  random: value
  foo: bar
